Repository Dacoband/SWD392-HairSalon, pull requests merged in 2024-11, with the labels that each got.

#35 Nhan/sit pull main
  Back_End/HairSalonSystem/HairSalonSystem.BusinessObject/Entities/Salary.cs
  Back_End/HairSalonSystem/HairSalonSystem.BusinessObject/Entities/Stylist.cs
  Back_End/HairSalonSystem/HairSalonSystem.BusinessObject/HairSalonDbContext.cs
  Back_End/HairSalonSystem/HairSalonSystem.DAOs/Implements/SalaryDAO.cs
  Back_End/HairSalonSystem/HairSalonSystem.DAOs/Interfaces/ISalaryDAO.cs
  Back_End/HairSalonSystem/HairSalonSystem.Repositories/Implement/SalaryRepository.cs
  Back_End/HairSalonSystem/HairSalonSystem.Repositories/Interface/ISalaryRepository.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Constant/APIEndPointConstant.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Constant/MessageConstant.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/AppointmentService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/MonthlySalaryService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/SalaryService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Interfaces/ISalaryService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/PayLoads/Requests/Salary/CreateSalaryModel.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/PayLoads/Requests/Salary/QuerySalary.cs
  Back_End/HairSalonSystem/HairSalonSystem/Controllers/SalaryController.cs
  Back_End/HairSalonSystem/HairSalonSystem/Program.cs
Labels: enhancement, Fix-Code

#41 Sit3
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/AppointmentService.cs
Labels: documentation, duplicate, enhancement, Fix-Code

#43 M anhh
  Back_End/HairSalonSystem/HairSalonSystem.Services/Constant/APIEndPointConstant.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Constant/MessageConstant.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/AppointmentService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Interfaces/IAppointmentService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/PayLoads/LoginResponse.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/PayLoads/Requests/Appointment/QueryStylist.cs
  Back_End/HairSalonSystem/HairSalonSystem/Controllers/AccountController.cs
  Back_End/HairSalonSystem/HairSalonSystem/Controllers/AppointmentController.cs
Labels: Fix-Code

#44 Sit3
  Back_End/HairSalonSystem/HairSalonSystem.Services/Constant/APIEndPointConstant.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Constant/MessageConstant.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/AppointmentService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Interfaces/IAppointmentService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/PayLoads/LoginResponse.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/PayLoads/Requests/Appointment/QueryStylist.cs
  Back_End/HairSalonSystem/HairSalonSystem/Controllers/AccountController.cs
  Back_End/HairSalonSystem/HairSalonSystem/Controllers/AppointmentController.cs
Labels: Fix-Code

#46 Manh Mrg
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/AppointmentService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/MemberService.cs
  Back_End/HairSalonSystem/HairSalonSystem.Services/Implements/StylistService.cs
  Back_End/HairSalonSystem/HairSalonSystem/Controllers/MemberController.cs
Labels: Fix-Code

#49 fix appointment authorize get by id
  Back_End/HairSalonSystem/HairSalonSystem/Controllers/AppointmentController.cs
Labels: Fix-Code
